---
include:
  - board: nice_nano_v2
    shield: crosses_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_POINTING=n
    artifact-name: crosses-peripheral-left
  - board: nice_nano_v2
    shield: crosses_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_POINTING=n
    artifact-name: crosses-peripheral-right
  - board: seeeduino_xiao_ble
    shield: crosses_dongle dongle_screen
    artifact-name: crosses-dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: crosses-settings-reset