---
include:
  - board: nice_nano_v2
    shield: crosses_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: crosses-left-peripheral
  - board: nice_nano_v2
    shield: crosses_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_POINTING=n -DSHIELD_OVERLAY_CONFIG_FILE=config/crosses_right_peripheral.overlay
    artifact-name: crosses-right-peripheral
  - board: nice_nano_v2
    shield: crosses_right
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    artifact-name: crosses-right-logging
  - board: seeeduino_xiao_ble
    shield: xiao_dongle dongle_screen
    artifact-name: xiao-dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao-settings-reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice-settings-reset