---
include:
  - board: nice_nano_v2
    shield: crosses_left
    artifact-name: crosses-left
  - board: nice_nano_v2
    shield: crosses_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: crosses-right
  - board: seeeduino_xiao_ble
    shield: xiao_dongle dongle_screen
    artifact-name: xiao-dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: crosses-settings-reset