CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_DISPLAY=y

CONFIG_DONGLE_SCREEN_LAYER_ACTIVE=y
CONFIG_DONGLE_SCREEN_MODIFIER_ACTIVE=y
CONFIG_DONGLE_SCREEN_OUTPUT_ACTIVE=y
CONFIG_DONGLE_SCREEN_BATTERY_ACTIVE=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
